version: '3.3'

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    image: ${IMAGE:-pipdevs/test}
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_SERVICE_HOST=elasticsearch
      - ELASTICSEARCH_SERVICE_PORT=9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    # container_name: elasticsearch
    environment:
      #- cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # ports:
    #   - "9200:9200"